### PR TITLE
Replace mem data store with file data store

### LINKED ISSUE #14: CLI credentials' JWT returns 403 after server restart and before OAuth flow triggered
# Problem
After nexus-proxy is restarted all JWTs obtained from `/cli/credentials` result in 403 responses, and the server logs claim it's because the principal "is not an organization member. Denying". Once a user has renewed their session by navigating to the browser and completing the OAuth flow, then the cli credential JWT authorizes successfully.

This is related to #3, which was closed but I found it to still be a problem.

# Reason
The principal is extracted from the JWT and then a credential store of previously authenticated OAuth tokens is checked for a matching principal. If no match is found then the principal is not considered an organization member. The JWT is stored by clients and the credential store is stored on the server, but currently that store is **in memory** only.

The credential store is wiped out when the server restarts because it lives in memory only. Therefore there is no matching token for the principal contained in the JWT provided by the client. Sessions are lost too, so when users navigate to the nexus-proxy they are forced to go through the OAuth flow again. When that happens, a new token is put into the credential store and subsequent calls with the previous JWT now have principal matches.

Since this proxy is primarily used in Kubernetes deployments, this loss of JWT validity becomes a problem every time there is an update of the Nexus pod or a pod gets rescheduled for planned and unplanned reasons.

### PR DESCRIPTION
**Pull request by JanekLehr**
Fixes #14 

Use a file-based data store to enable persisting the credential store beyond server restarts.

The in-memory store has been replaced completely because it is causes this bug. In fact, the file-based store behaves the same way as the in-mem if run in a container without a volume attached to persist the store. However, if a persistent volume is used then auth tokens continue to work after restart and before a fresh oauth flow.

### CODE REVIEW

**Comment by pires** [comment]
I'm sorry for the delay but I've been busy with completely unrelated work.

Now, thank you for putting the effort into this. However, this is not a new idea to me and I actually put the work before but didn't push because I concluded it was a bad idea to store such sensitive information. Let's look at #14 first and then come back at this.

**Comment by JanekLehr** [comment]
@pires Ah, I understand your security concern. How do you deal with this issue then, especially for CLI tools that pull from Nexus during local dev workflows or CI/CD automation? Do you have to make sure everyone logs in via the browser each time a new Pod launches?

**Comment by JanekLehr** [comment]
Hi @pires. This is a ping for my previous comment. Do you have the problem I mentioned in my earlier comment? How do you address it?

**Comment by pires** [comment]
Sorry once again but I'm no longer involved with this effort. @arochaf @flaviof can you help?

**Pull request closed without merging**
